name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        run: | 
          echo "${{ secrets.PASSWORD}}" | docker login ghcr.io -u "${{ secrets.USERNAME }}" --password-stdin

      - name: build backend image
        run: |
          docker buildx build \
            --tag ghcr.io/svacinar/garden_app_backend:latest \
            --platform=linux/arm/v7 --push ./garden_app_backend
      - name: build frontend image
        run: |
          docker buildx build \
            --tag ghcr.io/svacinar/garden_app_frontend:latest \
            --platform=linux/arm/v7 --push ./garden_app_frontend
