name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out Repository
        uses: actions/checkout@v2

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: build backend image
        run: |
          docker buildx build \
            --tag ghcr.io/svacinar/garden_app_backend:latest \
            --platform=linux/amd64,linux/arm32/v7 --push .
